// path/to/your/file
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */

  // Fixed the syntax here
  sidebar: [
    "intro",
    {
      type: 'category', // Added missing type
      label: 'My Category', // Added label for the category
      items: ['item1', 'item2'], // Added items for the category
    },
  ],
};

export default sidebars;
